<ResultsScreen>:
    layout: layout
    BoxLayout:
        id: layout
        orientation: "vertical"

        topBar: topBar
        lowerBar: lowerBar
        mainContent: mainContent
        
        # Top Bar
        BoxLayout:
            id: topBar
            mytext:mytext
            orientation: "horizontal"
            size_hint: (1, 0.2)
            Label:
                text: "corner"
                size_hint: (0.2, 1)
            Label:
                id: mytext
                text: "Main Banner!"

        # Main Content
        BoxLayout:
            id: mainContent
            orientation: "horizontal"

            #buttons: buttons
            graph: graph

            #BoxLayout:
            #    id: buttons
            #    orientation: "vertical"

                

            Image:
                id: graph
                source: 'graph.png'

        # Lower Bar
        BoxLayout:
            id: lowerBar
            orientation: "horizontal"
            words: words
            size_hint: (1, 0.2)
            pos_hint: {'bottom': 1}

            Button:
                text: "Back to menu"
                on_release:
                    app.results.stop_process()
                    app.sm.current = "home"

            Label:
                id: words
                text: "Here's a thing"

